#!/usr/bin/env python

# -*- coding: utf-8 -*-

from sys import argv, exit

from PyQt4 import QtGui, QtCore

from sms_main_window import Ui_SMSMain

if __name__ == "__main__":
    app = QtGui.QApplication(argv)

    SMSMain = QtGui.QMainWindow()
    ui = Ui_SMSMain()
    ui.setupUi(SMSMain)
    SMSMain.show()

    exit(app.exec_())
    

